#!/bin/bash

set -e

# Set variables
APPLICATIONS="$HOME/Applications"
DESTINATION="$APPLICATIONS/NiceDeck"
REPOSITORY="https://github.com/mateussouzaweb/nicedeck"
RELEASES="$REPOSITORY/releases/download"
FILE="nicedeck"
VERSION="v0.0.21"

# Determine file and version based on parameters
# First parameter define build and you can use 'gtk' or 'qt' builds
# Second parameter determined program version in the format 'x.x.x'
if [[ $1 == "gtk" || $1 == "qt" ]]; then
  FILE="$FILE-$1"
fi
if [[ -n $2 ]]; then
  VERSION="v$2"
fi

# Make sure applications folder exists
if [[ ! -d $APPLICATIONS ]]; then
  mkdir -p $APPLICATIONS
fi

# Download the program
echo "[INFO] Downloading $FILE version $VERSION..."
wget -q $RELEASES/$VERSION/$FILE -O $DESTINATION
echo "[INFO] Download completed!"

# Apply permissions 
chmod +x $DESTINATION
echo "[INFO] Program installed at $DESTINATION"

# Run the program
echo "[INFO] Running the program..."
$DESTINATION