#!/bin/bash

set -e
set -u

VERSION="v0.0.20"
REPOSITORY="https://github.com/mateussouzaweb/nicedeck"
FILE="$REPOSITORY/releases/download/$VERSION/nicedeck"

APPLICATIONS="$HOME/Applications"
DESTINATION="$APPLICATIONS/nicedeck"

# Make sure applications folder exists
if [ ! -d "$APPLICATIONS" ]; then
  mkdir -p $APPLICATIONS
fi

# Use flatpak when available
# Otherwise, install from binary
if [ -x "$(command -v flatpak)" ]; then

  # Download the program
  FILE="$FILE.flatpak"
  DESTINATION="$DESTINATION.flatpak"
  wget -q $FILE -O $DESTINATION

  # Install the program
  flatpak install --assumeyes $DESTINATION
  rm $DESTINATION

  # Run the program
  echo "[INFO] NiceDeck $VERSION installed with flatpak"
  echo "[INFO] Running the program..."
  flatpak run com.mateussouzaweb.NiceDeck

else

  # Download the program
  echo "[INFO] Downloading NiceDeck..."
  wget -q $BINARY -O $DESTINATION
  chmod +x $DESTINATION

  # Run the program
  echo "[INFO] NiceDeck $VERSION installed at $DESTINATION"
  echo "[INFO] Running the program..."
  $DESTINATION

fi