#!/bin/bash

set -e
set -u

# Set variables
VERSION="v0.0.20"
REPOSITORY="https://github.com/mateussouzaweb/nicedeck"
FILE="$REPOSITORY/releases/download/$VERSION/nicedeck"
APPLICATIONS="$HOME/Applications"
DESTINATION="$APPLICATIONS/nicedeck"

# Make sure applications folder exists
if [ ! -d "$APPLICATIONS" ]; then
  mkdir -p $APPLICATIONS
fi

# Download the program
echo "[INFO] Downloading NiceDeck..."
wget -q $BINARY -O $DESTINATION
chmod +x $DESTINATION

# Run the program
echo "[INFO] NiceDeck $VERSION installed at $DESTINATION"
echo "[INFO] Running the program..."
$DESTINATION