name: Create tag

on:
  push:
    branches:
      - master

jobs:
  create:
    name: Create
    if: contains(github.event.head_commit.message, 'Version')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Validate if is version commit
        id: validate-commit
        run: |
          REGEX="^Version [0-9]+\.[0-9]+\.[0-9]+$"
          COMMIT="${{ github.event.head_commit.message }}"
          if [[ $COMMIT =~ $REGEX ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        if: steps.validate-commit.outputs.valid == 'true'
        uses: actions/checkout@v4

      - name: Create and push new tag
        if: steps.validate-commit.outputs.valid == 'true'
        run: |
          # Extract tag and version from commit
          COMMIT="${{ github.event.head_commit.message }}"
          VERSION="$(echo $COMMIT | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')"
          TAG="v$VERSION"

          # Create and push new tag
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a $TAG -m "Version $VERSION"
          git push origin $TAG
